# Generated by Django 4.2.1 on 2024-02-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_items',
        ),
    ]
