# Generated by Django 5.0.1 on 2024-02-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_historicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
