# Generated by Django 4.2.11 on 2024-03-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_historicalrecord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=30),
        ),
    ]
