# Generated by Django 5.0.3 on 2024-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZOR PAY', 'FLUTTER PAY Payment')], default='COD', max_length=30),
        ),
    ]
